### ISSUE TITLE
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by lvothnrv** [JakubChm/nextjs-mdbreact#2]
Hello, I would need some help if you don't mind .. infact I'm trying to put mdbreact on my nextjs project and it tells me this .. I'm on the latest version of Next React Mdbreact ..
![91479683_1436325706547843_1628657237935259648_n](https://user-images.githubusercontent.com/62966130/78078082-94749100-73ba-11ea-9b7f-cfae870f2588.jpg)
![Capture d’écran 2020-04-01 à 01 45 37](https://user-images.githubusercontent.com/62966130/78078088-976f8180-73ba-11ea-90c7-e0558159e3bc.png)

**Comment by jakubchmura** [comment]
Thank you for the founded issue. I will try to check what's going on as soon as possible.

Best, Kuba

**Comment by jakubchmura** [comment]
Problem solved with the latest version.
